# TODO: Use language: :elixir when v1.4.0 is out.
language: erlang
otp_release:
  - 18.0
  - 18.3
  - 19.0
  - 19.1
sudo: false
before_script:
  - wget http://s3.hex.pm/builds/elixir/master.zip
  - unzip -d elixir master.zip
  - export PATH=$(pwd)/elixir/bin:${PATH}
  - epmd -daemon
  - mix deps.get --only test
script:
  - mix test
